version: '3.8'

services:
  application:
    build:
      context: .
      args:
        requirements_file: requirements.txt
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - mongo-db
    entrypoint: ["uvicorn", "api_server:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - app-network
    external_links:
      - app-network

  mongo-db:
    image: mongo:latest
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
    networks:
      - app-network
    external_links:
      - app-network
volumes:
  db-data:
    driver: local

networks:
  app-network:
    external: true