services:
  application:
    build:
      context: .
      args:
        requirements_file: requirements.txt
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - mongo-db
    entrypoint: ["uvicorn", "api_server:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - app-network
    container_name: app_container

  mongo-db:
    image: mongo:latest
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
    networks:
      - app-network
    container_name: mongodb_container

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: "mongo-db"
    depends_on:
      - mongo-db
    networks:
      - app-network
    container_name: mongo_express_container

volumes:
  db-data:
    driver: local

networks:
  app-network:
    name: app-network
    driver: bridge